# Generated by Django 3.2.19 on 2026-02-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], max_length=50, null=True),
        ),
    ]
