# Generated by Django 6.0.2 on 2026-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20260204_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube trailer URL', null=True),
        ),
    ]
