# Generated by Django 6.0.2 on 2026-02-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_seat_is_reserved_seat_reserved_at_seat_reserved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
        ),
    ]
